{
 "title": "RRI-Proxy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "SERVER",
    "label": "Proxy server",
    "query": "label_values(rri_prx_interface_estab_conns , server_name)"
   },
   {
    "name": "SOURCE",
    "label": "Source IP",
    "query": "label_values(rri_prx_proxy_request_count , addr)"
   },
   {
    "name": "DEST",
    "label": "Destination",
    "query": "label_values(rri_prx_proxy_request_count , host)"
   },
   {
    "name": "STATUS",
    "label": "Status",
    "query": "label_values(rri_prx_proxy_request_count , message)"
   },
   {
    "name": "INTERVAL",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Estab socket conns",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rri_prx_proxy_socket_estab_connections{addr=~\"[[SOURCE]]\", host=~\"[[DEST]]\", server_name=\"[[SERVER]]\" })"
    }
   ]
  },
  {
   "title": "Rate HTTP requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(rri_prx_interface_requests{addr=~\"[[SOURCE]]\", host=~\"[[DEST]]\", server_name=\"[[SERVER]]\"}[1m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Rate HTTP ERRORS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(rri_prx_proxy_request_count{code != \"200\",addr=~\"[[SOURCE]]\", host=~\"[[DEST]]\", server_name=\"[[SERVER]]\"}[1m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Requests per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rri_prx_proxy_request_count{message !~ \"unsupported protocol scheme.*\", addr=~\"[[SOURCE]]\", host=~\"[[DEST]]\", message=~\"[[STATUS]]\", server_name=\"[[SERVER]]\"}[$__interval]) ) > 0",
     "legendFormat": "Count requests"
    },
    {
     "expr": "max(rate(rri_prx_proxy_request_sec{message !~ \"unsupported protocol scheme.*\", addr=~\"[[SOURCE]]\", host=~\"[[DEST]]\", message=~\"[[STATUS]]\", server_name=\"[[SERVER]]\"}[$__interval])) > 0",
     "legendFormat": "Response time MAX"
    }
   ]
  },
  {
   "title": "HTTP errors ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Errors per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rri_prx_proxy_request_count{code != \"200\", server_name=\"[[SERVER]]\", message !~ \"unsupported protocol scheme.*\", host!~\"^[0-9]{1,3}\", addr=~\"[[SOURCE]]\", host=~\"[[DEST]]\", message=~\"[[STATUS]]\"}[$__interval])) by (code) > 0",
     "legendFormat": "count {{code}}"
    }
   ]
  },
  {
   "title": "Socket connection errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Errors per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rri_prx_proxy_socket_requests_error{ server_name=\"[[SERVER]]\"}[$__interval])) by (host, addr,error) ",
     "legendFormat": "{{addr}} -> {{host}} - {{error}}"
    }
   ]
  },
  {
   "title": "Socket established connections",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Established connections" }
   ],
   "targets": [
    {
     "expr": "sum(rri_prx_proxy_socket_estab_connections{addr=~\"[[SOURCE]]\", server_name=\"[[SERVER]]\", host=~\"[[DEST]]\"}) by (host, addr)",
     "legendFormat": "{{addr}} -> {{host}}"
    }
   ]
  },
  {
   "title": "Socket connections rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Reconnects per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rri_prx_proxy_socket_requests{addr=~\"[[SOURCE]]\", server_name=\"[[SERVER]]\", host=~\"[[DEST]]\"}[5m])) by (addr, host)",
     "legendFormat": "{{addr}} -> {{host}}"
    }
   ]
  },
  {
   "title": "Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Errors detailed",
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(delta(rri_prx_proxy_request_count{code != \"200\", server_name=\"[[SERVER]]\", message !~\"unsupported protocol scheme.*\", host !~ \"^[0-9]{1,3}\", addr=~\"[[SOURCE]]\", host=~\"[[DEST]]\", message=~\"[[STATUS]]\"}[$__range])) by (addr,host,method,message,uri) > 0"
      }
     ]
    },
    {
     "title": "HTTP long queries by range",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "max(rate(rri_prx_proxy_request_sec{server_name=\"[[SERVER]]\", host !~ \"^[0-9]{1,3}\", addr=~\"[[SOURCE]]\", host=~\"[[DEST]]\", message=~\"[[STATUS]]\"}[$__range])) by (addr,host,method,message,uri) > 0.100"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface estab connections",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(rri_prx_interface_estab_conns{server_name=\"[[SERVER]]\"}) by (addr, server_name)"
      }
     ]
    },
    {
     "title": "Estab socket conns",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 7, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rri_prx_interface_estab_conns{server_name=\"[[SERVER]]\"})"
      }
     ]
    },
    {
     "title": "GC histogram",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "go_gc_duration_seconds{server_name=\"[[SERVER]]\"}",
       "legendFormat": "GC time {{quantile}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Request per seconds",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 7, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(rate(rri_prx_interface_requests{server_name=\"[[SERVER]]\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Proccess FDS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{server_name=\"[[SERVER]]\"}",
       "legendFormat": "Open FDS"
      }
     ]
    },
    {
     "title": "Gorutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{server_name=\"[[SERVER]]\"}",
       "legendFormat": "Goroutines"
      }
     ]
    },
    {
     "title": "GC CPU time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "rate(go_gc_duration_seconds_sum{server_name=\"[[SERVER]]\"}[$__interval])",
       "legendFormat": "GC CPU time",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "GC CPU time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "rate(go_memstats_alloc_bytes{server_name=\"[[SERVER]]\"}[$__interval])",
       "legendFormat": "Alloc memory",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  }
 ]
}